sudo: required
services: docker
language: bash
env:
    global:
        - QEMU_VER=v2.9.1
        - DOCKER_REPO=maartje/grafana-multiarch
    matrix:
        - ARCH=amd64    VERSION=v4.6.3   QEMU_ARCH=x86_64 DOWNLOAD_URL="https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_4.6.3_amd64.deb"
        - ARCH=armhf    VERSION=v4.6.3   QEMU_ARCH=arm    DOWNLOAD_URL="https://github.com/fg2it/grafana-on-raspberry/releases/download/v4.6.3/grafana_4.6.3_armhf.deb"

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

before_script:
    - sudo apt-get -y install qemu-user-static
    - docker run --rm --privileged multiarch/qemu-user-static:register
script:
    - travis_wait sudo ./build.sh --arch="$ARCH" --version="$VERSION" --qemuarch="$QEMU_ARCH" --qemuversion="$QEMU_VER" --repo="$DOCKER_REPO" --goarch="$GO_ARCH" --downloadurl="$DOWNLOAD_URL" 
after_success:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker push $DOCKER_REPO
